/* Medjasi effects v1 — vizuelni sloj; ne mijenja Supabase podatke. */
(()=>{"use strict";
const reduce=window.matchMedia("(prefers-reduced-motion: reduce)").matches,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function buildBg(){if($(".fx-bg"))return;const d=document.createElement("div");d.className="fx-bg";d.setAttribute("aria-hidden","true");const sp=[[8,70,4,9],[31,40,3,12],[67,80,5,10],[90,55,3,13],[48,88,3,11],[78,30,4,14]].map(([l,t,s,du],i)=>'<i class="fx-sp" style="left:'+l+'%;top:'+t+'%;width:'+s+'px;height:'+s+'px;animation-duration:'+du+'s;animation-delay:-'+i*2+'s"></i>').join("");d.innerHTML='<div class="fx-beams"><div class="fx-beam l"></div><div class="fx-beam r"></div></div><div class="fx-lamp l"></div><div class="fx-lamp r"></div><div class="fx-fog"></div><div class="fx-court"><svg viewBox="0 0 1500 900" fill="none" stroke="#25e487" stroke-width="3" stroke-opacity=".5"><rect x="60" y="40" width="1380" height="820" rx="6"/><line x1="60" y1="450" x2="1440" y2="450"/><circle cx="750" cy="450" r="120"/><circle cx="750" cy="450" r="6" fill="#25e487"/><path d="M560 40A190 190 0 0 0 940 40"/><path d="M560 860A190 190 0 0 1 940 860"/><rect x="650" y="40" width="200" height="14" stroke="#1598ff"/><rect x="650" y="846" width="200" height="14" stroke="#1598ff"/></svg></div>'+sp+'<div class="fx-grain"></div><div class="fx-vig"></div>';document.body.prepend(d);if(!reduce){let t=0;addEventListener("scroll",()=>{if(t)return;t=requestAnimationFrame(()=>{t=0;d.querySelector(".fx-court").style.transform="translateY("+(-Math.min(scrollY,900)*.12)+"px)"})},{passive:true})}}
let io;function scanReveal(){if(!("IntersectionObserver"in window))return;io=io||new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("fx-in");io.unobserve(e.target)}}),{threshold:.08,rootMargin:"0px 0px -30px 0px"});$$(".section.active .card:not(.fx-reveal),.section.active .v10-kpi:not(.fx-reveal),.section.active .match-row:not(.fx-reveal),.section.active .team-card:not(.fx-reveal),.section.active .player-card:not(.fx-reveal)").forEach(el=>{el.classList.add("fx-reveal");if(el.getBoundingClientRect().top<innerHeight)requestAnimationFrame(()=>el.classList.add("fx-in"));else io.observe(el)})}
const shown=new Map;function countUp(el,to){const id=el.id||Math.random(),from=shown.get(id)??0;if(from===to)return;shown.set(id,to);if(reduce||Math.abs(to-from)<2){el.textContent=String(to);return}const t0=performance.now(),dur=900;(function step(now){const p=Math.min(1,(now-t0)/dur),e=1-Math.pow(1-p,3);el.textContent=String(Math.round(from+(to-from)*e));if(p<1)requestAnimationFrame(step)})(t0)}
function watchCounters(){$["statTeams","statPlayers","statMatches","statGoals"].forEach?.(()=>{});["statTeams","statPlayers","statMatches","statGoals"].forEach(id=>{const el=document.getElementById(id);if(!el||el.dataset.fxw)return;el.dataset.fxw="1";new MutationObserver(()=>{const v=parseInt(el.textContent,10);if(!isNaN(v)&&el.dataset.fxanim!=="1"){el.dataset.fxanim="1";countUp(el,v);setTimeout(()=>delete el.dataset.fxanim,950)}}).observe(el,{childList:true,characterData:true,subtree:true})})}
const lastScore=new Map;function goalFlash(){$$(".match-row:has(.status.live),.live-scoreboard").forEach((row,i)=>{const el=row.querySelector(".score,.live-score");if(!el)return;const names=[...row.querySelectorAll(".team-name")].map(n=>n.textContent.trim()).join("|")||"ls"+i,txt=el.textContent.replace(/\s+/g,""),prev=lastScore.get(names);if(prev!==undefined&&prev!==txt&&!reduce){el.classList.remove("fx-goal");void el.offsetWidth;el.classList.add("fx-goal")}lastScore.set(names,txt)})}
function watchBell(){const b=document.getElementById("notificationBadge");if(!b||b.dataset.fxw)return;b.dataset.fxw="1";new MutationObserver(()=>{if(b.hidden||reduce)return;const bell=document.getElementById("notificationBell");bell?.classList.remove("fx-ring");void bell?.offsetWidth;bell?.classList.add("fx-ring")}).observe(b,{childList:true,characterData:true,subtree:true,attributes:true,attributeFilter:["hidden"]})}
let tm=0;function tick(){clearTimeout(tm);tm=setTimeout(()=>{try{scanReveal();goalFlash();watchCounters();watchBell()}catch(e){console.warn("fx:",e)}},120)}
function init(){try{buildBg();document.documentElement.classList.add("fx-ready");tick();new MutationObserver(tick).observe(document.querySelector("main")||document.body,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:["class"]})}catch(e){console.warn("fx init:",e)}}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init):init();
})();