/* Pogodi fan game module */
(() => {
  "use strict";
  const $ = id => document.getElementById(id);
  const E = v => String(v ?? "").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  const sb = () => window.supabaseClient;
  const user = () => (typeof currentUser !== "undefined" ? currentUser : null);
  const prof = () => (typeof currentProfile !== "undefined" ? currentProfile : null);
  const isAdm = () => prof()?.role === "admin";
  const MT = () => (typeof matches !== "undefined" ? matches : []);
  const PL = () => (typeof players !== "undefined" ? players : []);
  const TM = () => (typeof teams !== "undefined" ? teams : []);
  const tname = id => TM().find(t=>String(t.id)===String(id))?.name || "Ekipa";
  const pname = id => PL().find(p=>String(p.id)===String(id))?.name || "Igrač";
  const note = (m,t="success") => typeof toast === "function" ? toast(m,t) : alert(m);
  const fmt = v => { try { return new Date(v).toLocaleString("bs-BA",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}); } catch { return ""; } };
  const title = m => `${tname(m.home_team_id)} – ${tname(m.away_team_id)}`;
  const win = (s,o,b) => Math.floor(Number(s||0)*Number(o||0)*(b?1.5:1));
  const S={tab:"matches",loading:false,err:null,wallet:null,markets:[],picks:[],ledger:[],board:[],shop:[],inv:[],follows:[],fund:{},stats:{},votes:{},mvp:{},profiles:[],sel:null};
  const TABS=[["matches","🎯 Pogodi"],["live","🔴 Live"],["mine","🎟️ Tiketi"],["fanbase","🧑‍🤝‍🧑 Fan Base"],["board","🏅 Tabela navijača"],["shop","🛍️ Fan Shop"],["collection","👑 Kolekcija"],["club","💚 Moja tribina"],["mvp","⭐ MVP"]];
  const active=()=>MT().filter(m=>m.status==="scheduled"||m.status==="live").sort((a,b)=>new Date(a.match_date||0)-new Date(b.match_date||0));
  const upcoming=()=>active().filter(m=>m.status==="scheduled");
  const finished=()=>MT().filter(m=>m.status==="finished").sort((a,b)=>new Date(b.match_date||0)-new Date(a.match_date||0));
  async function refresh(){
    if(S.loading||!sb())return; S.loading=true;
    try{
      const u=user();
      const [mk,shop,fund,board]=await Promise.all([sb().from("fan_markets").select("*").eq("status","open").order("created_at"),sb().from("fan_shop_items").select("*").eq("active",true).order("price"),sb().from("fan_team_fund").select("*"),sb().rpc("fan_leaderboard")]);
      if(mk.error&&/relation|does not exist|schema cache|function/i.test(mk.error.message||"")){S.err="setup";return;}
      S.err=null; S.markets=mk.data||[]; S.shop=shop.data||[]; S.fund=Object.fromEntries((fund.data||[]).map(r=>[String(r.team_id),r.total])); S.board=board.data||[];
      if(S.board.length){const ids=S.board.map(r=>r.user_id).filter(Boolean);const {data:styles}=await sb().rpc("fan_public_cosmetics",{p_users:ids});const byId=Object.fromEntries((styles||[]).map(r=>[String(r.user_id),r]));S.board=S.board.map(r=>({...r,...(byId[String(r.user_id)]||{})}));}
      if(u){await sb().rpc("fan_ensure_wallet");const [w,pk,led,inv,votes,fol]=await Promise.all([sb().from("fan_wallets").select("*").eq("user_id",u.id).maybeSingle(),sb().from("fan_picks").select("*,fan_markets(label)").eq("user_id",u.id).order("created_at",{ascending:false}).limit(60),sb().from("fan_ledger").select("*").eq("user_id",u.id).order("created_at",{ascending:false}).limit(15),sb().from("fan_inventory").select("*").eq("user_id",u.id),sb().from("fan_mvp_votes").select("match_id").eq("voter",u.id),sb().from("fan_team_follows").select("team_id").eq("user_id",u.id)]);S.wallet=w.data||null;S.picks=pk.data||[];S.ledger=led.data||[];S.inv=inv.data||[];S.follows=(fol.data||[]).map(x=>String(x.team_id));S.votes=Object.fromEntries((votes.data||[]).map(v=>[String(v.match_id),true]));}else{S.wallet=null;S.picks=[];S.ledger=[];S.inv=[];S.follows=[];S.votes={};}
      S.stats={}; await Promise.all(active().slice(0,12).map(async m=>{const {data}=await sb().rpc("fan_market_stats",{p_match:String(m.id)});(data||[]).forEach(r=>S.stats[r.market_id]=Number(r.picks));}));
      S.mvp={}; await Promise.all(finished().slice(0,4).map(async m=>{const {data}=await sb().rpc("fan_mvp_results",{p_match:String(m.id)});S.mvp[String(m.id)]=data||[];}));
      if(isAdm()&&!S.profiles.length){const {data}=await sb().from("profiles").select("id,username").order("username");S.profiles=data||[];}
    }catch(e){console.error("Pogodi:",e);}finally{S.loading=false;render();}
  }
  function group(list){const g={result:[],total:[],red_card:[],exact:[],scorer:[],player_2plus:[]};list.forEach(x=>g[x.kind]?.push(x));return g;}
  function opt(m,total){const mine=S.picks.find(p=>p.market_id===m.id),n=S.stats[m.id]||0,pct=total?Math.round(100*n/total):null;return `<button class="fg-opt ${mine?"is-mine":""}" data-act="pick" data-id="${E(m.id)}" ${mine?"disabled":""}><span>${E(m.label)}</span><b>${Number(m.odds).toFixed(2)}</b>${mine?`<small>✓ tvoj pogodak (${mine.stake})</small>`:pct!==null?`<small>${pct}% navijača</small>`:""}</button>`;}
  function block(t,l){if(!l.length)return"";const total=l.reduce((s,m)=>s+(S.stats[m.id]||0),0);return `<div class="fg-group"><h4>${t}</h4><div class="fg-opts">${l.map(m=>opt(m,total)).join("")}</div></div>`;}
  function scorer(t,l,m){if(!l.length)return"";const by=id=>l.filter(x=>PL().find(p=>String(p.id)===String(x.player_id))?.team_id==id);return `<details class="fg-group fg-more"><summary>${t} <small>(${l.length})</small></summary><div class="fg-cols">${[m.home_team_id,m.away_team_id].map(id=>{const x=by(id);return x.length?`<div class="fg-team-col"><h5>${E(tname(id))}</h5><div class="fg-opts">${x.map(v=>opt(v,0)).join("")}</div></div>`:""}).join("")}</div></details>`;}
    function tabLive(){
    const list=active().filter(m=>m.status==='live'&&S.markets.some(k=>k.match_id===String(m.id)));
    if(!list.length)return '<div class="card fg-empty"><h3>🔴 Trenutno nema live pogađanja</h3><p>Kad utakmica bude uživo, ovdje će se otvoriti live kvote.</p></div>';
    return '<div class="card fg-live-note"><b>🔴 LIVE KVOTE</b><p>Kvote se automatski mijenjaju nakon gola, kartona i promjene rezultata. Tvoj već odigrani tiket zadržava kvotu koju je imao u trenutku uplate.</p></div>'+list.map(m=>{const g=group(S.markets.filter(k=>k.match_id===String(m.id)));return '<article class="card fg-match fg-live-card"><header><div class="fg-teams"><b>'+E(tname(m.home_team_id))+'</b><strong>'+E((m.home_score||0)+':'+(m.away_score||0))+'</strong><b>'+E(tname(m.away_team_id))+'</b></div><small>🔴 UŽIVO · '+E(m.current_minute||0)+"'</small></header>"+block('Ishod utakmice',g.result)+block('Ukupno golova',g.total)+block('Crveni karton',g.red_card)+scorer('⚽ Ko daje gol',g.scorer,m)+scorer('🔥 Ko daje 2+ gola',g.player_2plus,m)+'</article>';}).join('');
  }
  function tabTickets(){
    if(!user())return '<div class="card fg-empty"><p>Prijavi se da pratiš svoje tikete.</p></div>';
    const open=S.picks.filter(p=>p.status==='open'),done=S.picks.filter(p=>p.status!=='open');
    const ticketRows=list=>list.map(p=>{const m=MT().find(x=>String(x.id)===p.match_id);const cl=p.status==='won'?'win':p.status==='lost'?'lose':p.status==='void'?'void':'wait';const txt=p.status==='won'?'Pogođeno':p.status==='lost'?'Promašeno':p.status==='void'?'Poništeno':'Aktivno';const live=m?.status==='live';return '<div class="fg-ticket-row"><div><b>'+E(p.fan_markets?.label||'Pogodak')+'</b><small>'+E(m?title(m):'')+' · '+(live?'🔴 LIVE · ':'')+'kvota '+Number(p.odds).toFixed(2)+' · ulog '+p.stake+'</small></div><div class="fg-r"><span class="fg-badge '+cl+'">'+txt+'</span><small>'+((p.status==='won'||p.status==='void')?'+'+p.payout:'potencijalno '+win(p.stake,p.odds,p.boosted))+'</small></div></div>';}).join('');
    return '<div class="card"><div class="fg-card-title-row"><div><h3>🎟️ Moji tiketi</h3><p class="fg-hint">Svaki tiket pamti kvotu u trenutku kada si ga odigrao.</p></div><button class="btn btn-small" onclick="window.openFanTickets?.()">Otvori profil</button></div><h4 class="fg-subtitle">Aktivni</h4>'+(ticketRows(open)||'<p class="fg-hint">Nema aktivnih tiketa.</p>')+'<h4 class="fg-subtitle">Istorija</h4>'+(ticketRows(done)||'<p class="fg-hint">Nema završenih tiketa.</p>')+'</div>';
  }
  function tabCollection(){
    if(!user())return '<div class="card fg-empty"><p>Prijavi se da vidiš svoju kolekciju.</p></div>';
    const owned=S.shop.filter(i=>S.inv.some(x=>x.item_id===i.id));
    if(!owned.length)return '<div class="card fg-empty"><h3>👑 Kolekcija je prazna</h3><p>Posjeti Fan Shop i uzmi prvi predmet koji će se vidjeti kroz Community i Chat.</p><button class="btn btn-green" data-act="tab" data-id="shop">Otvori Fan Shop</button></div>';
    return '<div class="card"><h3>👑 Moja kolekcija</h3><p class="fg-hint">Ono što aktiviraš automatski se prikazuje u Communityju, profilu i Chatu.</p><div class="fg-collection">'+owned.map(i=>{const on=!!S.inv.find(x=>x.item_id===i.id)?.equipped;const preview=i.kind==='emoji_pack'?i.value.split(',').map(E).join(' '):i.kind==='badge'?E(i.value):i.kind==='name_color'?'<span style="color:'+E(i.value)+'">Ime</span>':i.kind==='frame'?'<span class="fg-name has-frame" style="border-color:'+E(i.value)+'">Ime</span>':'<small>'+E(i.value)+'</small>';return '<div class="fg-collection-item '+(on?'equipped':'')+'"><div class="fg-prev">'+preview+'</div><b>'+E(i.name)+'</b><small>'+(on?'✓ Aktivno':'Kupljeno')+'</small><button class="btn btn-small '+(on?'btn-green':'')+'" data-act="equip" data-id="'+i.id+'" data-on="'+(on?0:1)+'">'+(on?'Skini':'Aktiviraj')+'</button></div>';}).join('')+'</div></div>';
  }
  function tabClub(){
    if(!user())return '<div class="card fg-empty"><p>Prijavi se da napraviš svoju tribinu.</p></div>';
    const followSet=new Set(S.follows);
    const rows=TM().map(t=>{const on=followSet.has(String(t.id));return '<div class="fg-club-row"><div><b>'+E(t.name)+'</b><small>💚 Fond: '+Number(S.fund[String(t.id)]||0)+' poena</small></div><button class="btn btn-small '+(on?'btn-green':'')+'" data-act="follow" data-id="'+E(t.id)+'">'+(on?'✓ Pratiš':'Prati ekipu')+'</button></div>';}).join('');
    const opts=TM().map(t=>'<option value="'+E(t.id)+'">'+E(t.name)+'</option>').join('');
    return '<div class="card"><h3>💚 Moja tribina</h3><p class="fg-hint">Izaberi ekipe koje pratiš. Praćenje je dio tvog fan identiteta.</p>'+rows+'</div><div class="card"><h3>💚 Podrži ekipu</h3><div class="fg-form"><select id="fgClubTeam">'+opts+'</select><input id="fgClubAmt" type="number" min="1" max="100" value="10"><button class="btn btn-green" data-act="clubDonate">Pokloni poene</button></div></div>';
  }

  function tabMatches(){const list=upcoming().filter(m=>S.markets.some(k=>k.match_id===String(m.id)));if(!list.length)return `<div class="card fg-empty"><h3>Trenutno nema utakmica za pogađanje</h3><p>Čim admin otvori ponude, pojaviće se ovdje.</p></div>`;return list.map(m=>{const g=group(S.markets.filter(k=>k.match_id===String(m.id)));return `<article class="card fg-match"><header><div class="fg-teams"><b>${E(tname(m.home_team_id))}</b><i>vs</i><b>${E(tname(m.away_team_id))}</b></div><small>${m.status==="live"?"🔴 UŽIVO · "+(m.current_minute||0)+"'":(m.round?`Kolo ${E(m.round)} · `:"")+E(fmt(m.match_date))}</small></header>${block("Ishod utakmice",g.result)}${block("Ukupno golova",g.total)}${block("Crveni karton",g.red_card)}${scorer("⚽ Ko daje gol",g.scorer,m)}${scorer("🔥 Ko daje 2+ gola",g.player_2plus,m)}${g.exact.length?`<details class="fg-group fg-more"><summary>🎯 Tačan rezultat <small>(${g.exact.length})</small></summary><div class="fg-opts">${g.exact.map(x=>opt(x,0)).join("")}</div></details>`:""}</article>`}).join("");}
  function tabMine(){if(!user())return `<div class="card fg-empty"><p>Prijavi se da vidiš svoje pogodke.</p></div>`;const b={open:["Čeka","wait"],won:["Pogođeno","win"],lost:["Promašeno","lose"],void:["Poništeno","void"]};const rows=S.picks.map(p=>{const m=MT().find(x=>String(x.id)===p.match_id),[txt,cl]=b[p.status]||b.open;return `<div class="fg-row"><div><b>${E(p.fan_markets?.label||"Pogodak")}</b><small>${m?E(title(m)):""} · kvota ${Number(p.odds).toFixed(2)} · ulog ${p.stake}</small></div><div class="fg-r"><span class="fg-badge ${cl}">${txt}</span><small>${p.status==="won"||p.status==="void"?`+${p.payout}`:p.status==="open"?`dobitak ${win(p.stake,p.odds,p.boosted)}`:""}</small></div></div>`}).join("");return `<div class="card"><h3>Moji pogoci</h3>${rows||`<p class="fg-hint">Još nisi pogodio nijednu ponudu.</p>`}</div><details class="card fg-more"><summary>Istorija poena</summary>${S.ledger.map(l=>`<div class="fg-row slim"><span>${E(l.reason)}</span><b class="${l.delta>0?"pos":"neg"}">${l.delta>0?"+":""}${l.delta}</b></div>`).join("")||`<p class="fg-hint">Nema promjena.</p>`}</details>`;}
  function styled(r){const c=r.name_color?'style="color:'+E(r.name_color)+'"':'';const fr=r.frame?'style="border-color:'+E(r.frame)+';box-shadow:0 0 12px '+E(r.frame)+'55"':'';const badge=r.badge?'<span class="fan-inline-badge">'+E(r.badge)+'</span>':'';const title=r.title?'<small class="fg-title">'+E(r.title)+'</small>':'';return '<span class="fg-name '+(r.frame?'has-frame':'')+'" '+fr+'><span '+c+'>'+badge+E(r.username||'Navijač')+'</span></span>'+title;}
  function fanLevel(){
  const ledgerPositive=S.ledger.filter(x=>Number(x.delta)>0).reduce((s,x)=>s+Number(x.delta||0),0);
  const picks=S.picks.length, wins=S.picks.filter(x=>x.status==="won").length;
  const xp=ledgerPositive+(picks*5)+(wins*15)+(S.inv.length*10)+(S.follows.length*5);
  return {xp,level:Math.max(1,Math.floor(xp/100)+1,next:(Math.floor(xp/100)+1)*100};
}
function fanAchievements(){
  const a=[];const wins=S.picks.filter(x=>x.status==="won").length;
  if(S.picks.length>=1)a.push(["🎯","Prvi pogodak","Odigran prvi fan tiket"]);
  if(wins>=5)a.push(["🔥","Vruća forma","5 pogođenih tiketa"]);
  if(S.inv.length>=1)a.push(["🛍️","Kolekcionar","Kupljen prvi Fan Shop predmet"]);
  if(S.follows.length>=1)a.push(["💚","Tribina","Pratiš barem jednu ekipu"]);
  if(S.votes&&Object.keys(S.votes).length>=1)a.push(["⭐","MVP glasač","Glasao si za MVP-a"]);
  if(S.ledger.some(x=>String(x.reason||"").toLowerCase().includes("daily")))a.push(["🎁","Redovni navijač","Iskorišten dnevni bonus"]);
  return a;
}
function tabFanBase(){
  if(!user())return '<div class="card fg-empty"><h3>🧑‍🤝‍🧑 Fan Base</h3><p>Prijavi se da pratiš svoj fan napredak.</p></div>';
  const l=fanLevel(),a=fanAchievements(),pct=Math.min(100,Math.round((l.xp%100)));
  const favBox='<div class="card"><h3>⭐ Favoriti</h3><p class="fg-hint">Favoriti ekipe i igrača koje si označio na njihovim profilima.</p><button class="btn btn-small" onclick="window.showSection(\'teams\')">Ekipe</button> <button class="btn btn-small" onclick="window.showSection(\'players\')">Igrači</button></div>';
  return '<div class="card"><h3>🧑‍🤝‍🧑 Moj Fan Base</h3><div class="fg-kv"><span>Nivo navijača</span><b>LVL '+l.level+'</b></div><div class="fg-kv"><span>XP</span><b>'+l.xp+' / '+l.next+'</b></div><p class="fg-hint">XP dobijaš kroz tikete, pogođene prognoze, kolekciju, praćenje ekipa, MVP glasanje i dnevnu aktivnost.</p><div class="fg-kv"><span>Napredak</span><b>'+pct+'%</b></div></div>'+favBox+'<div class="card"><h3>🏆 Dostignuća</h3>'+(a.length?a.map(x=>'<div class="fg-row slim"><span>'+x[0]+' <b>'+E(x[1])+'</b><small>'+E(x[2])+'</small></span><span>✓</span></div>').join(""):'<p class="fg-hint">Još nema otključanih dostignuća. Kreni kroz Fan Game.</p>')+'</div>';
}
function tabBoard(){if(!S.board.length)return `<div class="card fg-empty"><p>Tabela navijača je još prazna.</p></div>`;const me=user()?.id;return `<div class="card"><h3>🏅 Tabela navijača</h3>${S.board.map((r,i)=>`<div class="fg-row ${r.user_id===me?"me":""}"><div><b>${["🥇","🥈","🥉"][i]||`${i+1}.`}</b> ${styled(r)}<small>${r.won}/${r.picks} pogođeno</small></div><b class="fg-pts">⭐ ${r.balance}</b></div>`).join("")}</div>`;}
  function tabShop(){if(!user())return `<div class="card fg-empty"><p>Prijavi se da koristiš prodavnicu.</p></div>`;const owned=new Map(S.inv.map(i=>[i.item_id,i])),kinds={name_color:"Boja imena",frame:"Okviri",badge:"Bedževi",title:"Titule",emoji_pack:"😀 Emoji paketi"};const shop=Object.entries(kinds).map(([k,l])=>{const items=S.shop.filter(i=>i.kind===k);if(!items.length)return"";return `<div class="card"><h3>${l}</h3><div class="fg-shop">${items.map(i=>{const o=owned.get(i.id),preview=k==="name_color"?`<span style="color:${E(i.value)}">Ime</span>`:k==="frame"?`<span class="fg-name has-frame" style="border-color:${E(i.value)}">Ime</span>`:k==="badge"?E(i.value):k==="emoji_pack"?i.value.split(",").map(E).join(" "):`<small>${E(i.value)}</small>`;return `<div class="fg-item"><div class="fg-prev">${preview}</div><b>${E(i.name)}</b><small>${E(i.description||"")}</small>${o?`<button class="btn btn-small ${o.equipped?"btn-green":""}" data-act="equip" data-id="${i.id}" data-on="${o.equipped?0:1}">${o.equipped?"✓ Nosiš":"Stavi"}</button>`:`<button class="btn btn-small" data-act="buy" data-id="${i.id}">⭐ ${i.price}</button>`}</div>`}).join("")}</div></div>`}).join("");const fund=TM().map(t=>`<option value="${E(t.id)}">${E(t.name)} (${S.fund[String(t.id)]||0})</option>`).join("");return shop+`<div class="card"><h3>💚 Navijački fond ekipe</h3><div class="fg-form"><select id="fgFundTeam">${fund}</select><input id="fgFundAmt" type="number" min="1" max="100" value="10"><button class="btn btn-green" data-act="donate">Pokloni</button></div></div>`;}
  function tabMvp(){const fin=finished().slice(0,4);if(!fin.length)return `<div class="card fg-empty"><p>MVP glasanje se otvara kad se završi prva utakmica.</p></div>`;return fin.map(m=>{const id=String(m.id),pl=PL().filter(p=>[String(m.home_team_id),String(m.away_team_id)].includes(String(p.team_id)));const top=(S.mvp[id]||[]).slice(0,3).map((r,i)=>`<div class="fg-row slim"><span>${["🥇","🥈","🥉"][i]} ${E(pname(r.player_id))}</span><b>${r.votes}</b></div>`).join("");const form=!user()?`<p class="fg-hint">Prijavi se da glasaš.</p>`:S.votes[id]?`<p class="fg-hint">✅ Već si glasao za ovu utakmicu.</p>`:`<div class="fg-form"><select id="mvpP-${E(id)}">${pl.map(p=>`<option value="${E(p.id)}">${E(p.name)} (${E(tname(p.team_id))})</option>`).join("")}</select><select id="mvpX-${E(id)}"><option value="0">Običan glas</option><option value="2">Jači glas (−2)</option><option value="5">Jak glas (−5)</option><option value="10">Najjači glas (−10)</option></select><button class="btn btn-green" data-act="mvp" data-id="${E(id)}">Glasaj</button></div>`;return `<article class="card"><h3>${E(title(m))} <small>${m.home_score||0}:${m.away_score||0}</small></h3>${top}${form}</article>`}).join("");}
  function tabAdmin(){if(!isAdm())return"";const open=new Map();S.markets.forEach(k=>open.set(k.match_id,(open.get(k.match_id)||0)+1));const rows=MT().filter(m=>m.status!=="finished"||open.has(String(m.id))).slice(0,14).map(m=>{const id=String(m.id),n=open.get(id)||0,act=m.status==="finished"?`<button class="btn btn-green btn-small" data-act="settle" data-id="${E(id)}">✅ Obračunaj poene</button>`:!n?`<button class="btn btn-small" data-act="gen" data-id="${E(id)}">➕ Otvori ponudu</button>`:"";return `<div class="fg-adm"><div class="fg-row"><div><b>${E(title(m))}</b><small>${E(m.status)} · ${E(fmt(m.match_date))} · ponuda: ${n}</small></div>${act}</div></div>`}).join("");const users=S.profiles.map(p=>`<option value="${E(p.id)}">${E(p.username||p.id)}</option>`).join("");return `<div class="card"><h3>Utakmice i ponude</h3>${rows||`<p class="fg-hint">Nema utakmica.</p>`}</div><div class="card"><h3>🎁 Dodijeli poene</h3><div class="fg-form"><select id="grU">${users}</select><input id="grA" type="number" value="20" min="-1000" max="1000"><input id="grR" placeholder="Razlog" maxlength="80"><button class="btn btn-green" data-act="grant">Dodijeli</button></div></div>`;}
  function render(){const root=$("gameRoot");if(!root)return;if(S.err==="setup"){root.innerHTML=`<div class="card fg-empty"><h3>Igra još nije aktivirana</h3><p>Pokreni SQL migraciju iz repoa nakon provjere.</p></div>`;return;}const tabs=[...TABS];if(isAdm())tabs.push(["admin","⚙️ Admin"]);const body=({matches:tabMatches,live:tabLive,mine:tabTickets,fanbase:tabFanBase,board:tabBoard,shop:tabShop,collection:tabCollection,club:tabClub,mvp:tabMvp,admin:tabAdmin}[S.tab]||tabMatches)();root.innerHTML=`<div class="card fg-head"><div><div class="fg-bal">⭐ <b>${E(S.wallet?.balance??"…")}</b> <span>poena navijača</span></div><p>Virtuelni fan poeni • bez novca i bez stvarne vrijednosti.</p></div>${user()?`<button class="btn btn-green" data-act="daily">🎁 Dnevni bonus +10</button>`:`<button class="btn btn-green" onclick="showSection('login')">🔐 Prijavi se</button>`}</div><div class="fg-tabs">${tabs.map(([id,l])=>`<button class="${S.tab===id?"active":""}" data-act="tab" data-id="${id}">${l}</button>`).join("")}</div><div class="fg-body">${body}</div>`;}
  async function rpc(n,a,msg){const {data,error}=await sb().rpc(n,a);if(error){note(error.message,"error");return{error};}if(msg)note(msg);return{data};}
  async function adminAction(action,payload,msg){const session=await sb().auth.getSession();const token=session.data?.session?.access_token;if(!token){note("Sesija je istekla.","error");return{error:new Error("Unauthorized")};}try{const res=await fetch(SUPABASE_URL+"/functions/v1/fan-admin-action",{method:"POST",headers:{Authorization:"Bearer "+token,"Content-Type":"application/json"},body:JSON.stringify({action,...payload})});const json=await res.json().catch(()=>({}));if(!res.ok){note(json.error||"Admin akcija nije uspjela.","error");return{error:new Error(json.error||"Admin action failed")};}if(msg)note(msg);return{data:json.data};}catch(error){note(error.message||"Greška mreže.","error");return{error};}}
  function openPick(id){if(!user())return showSection("login");const m=S.markets.find(x=>x.id===id);if(!m)return;S.sel=m;const bal=S.wallet?.balance||0,max=Math.min(50,bal);showModal(`<div class="fg-modal"><h3>🎯 ${E(m.label)}</h3><p class="fg-hint">${E(title(MT().find(x=>String(x.id)===m.match_id)||{}))}</p><div class="fg-kv"><span>Kvota</span><b>${Number(m.odds).toFixed(2)}</b></div><label class="fg-lab">Ulog</label><input id="fgStake" type="number" min="1" max="${max}" value="${Math.min(10,max)||1}"><label class="fg-check"><input id="fgBoost" type="checkbox"> 🚀 Pojačivač (+50%)</label><div class="fg-kv big"><span>Mogući dobitak</span><b id="fgWin">0</b></div><button class="btn btn-green" data-act="confirm">Potvrdi pogodak</button></div>`);updateWin();}
  function updateWin(){const m=S.sel,w=$("fgWin");if(m&&w)w.textContent=win($("fgStake")?.value,m.odds,$("fgBoost")?.checked);}
  window.openFanTickets=async function(){
    if(!user()){showSection('login');return;}
    const {data,error}=await sb().from('fan_picks').select('id,match_id,kind,stake,odds,boosted,status,payout,created_at,fan_markets(label)').eq('user_id',user().id).order('created_at',{ascending:false}).limit(100);
    if(error){note(error.message,'error');return;}
    const rows=(data||[]).map(p=>{const m=MT().find(x=>String(x.id)===String(p.match_id));const cl=p.status==='won'?'win':p.status==='lost'?'lose':p.status==='void'?'void':'wait';const txt=p.status==='won'?'Pogođeno':p.status==='lost'?'Promašeno':p.status==='void'?'Poništeno':'Aktivno';return '<div class="fg-ticket-row"><div><b>'+E(p.fan_markets?.label||'Pogodak')+'</b><small>'+E(m?title(m):'')+' · kvota '+Number(p.odds).toFixed(2)+' · ulog '+p.stake+' · '+fmt(p.created_at)+'</small></div><div class="fg-r"><span class="fg-badge '+cl+'">'+txt+'</span><small>'+((p.status==='won'||p.status==='void')?'+'+p.payout:'')+'</small></div></div>';}).join('');
    showModal('<div class="fg-ticket-modal"><h3>🎟️ Moji tiketi</h3><p class="fg-hint">Sve ostaje u virtuelnim fan poenima. Kvote na tiketu ostaju zaključane na vrijednosti koju si dobio pri uplati.</p>'+(rows||'<p class="fg-hint">Još nemaš nijedan tiket.</p>')+'</div>');
  };

  async function onClick(e){const b=e.target.closest("[data-act]");if(!b)return;const a=b.dataset.act,id=b.dataset.id;if(a==="tab"){S.tab=id;render();}else if(a==="pick")openPick(id);else if(a==="confirm"){b.disabled=true;const r=await rpc("fan_place_pick",{p_market:S.sel.id,p_stake:Math.floor(Number($("fgStake")?.value)),p_boost:!!$("fgBoost")?.checked},"Pogodak je sačuvan! 🎯");b.disabled=false;if(!r.error){hideModal();S.sel=null;refresh();}}else if(a==="daily"){const r=await rpc("fan_claim_daily",{},"+10 poena! 🎁");if(!r.error)refresh();}else if(a==="buy"){const r=await rpc("fan_buy_item",{p_item:Number(id)},"Kupljeno! 🛍️");if(!r.error)refresh();}else if(a==="equip"){const r=await rpc("fan_equip_item",{p_item:Number(id),p_on:b.dataset.on==="1"});if(!r.error)refresh();}else if(a==="donate"){const r=await rpc("fan_team_donate",{p_team:$("fgFundTeam").value,p_amount:Number($("fgFundAmt").value)},"Hvala na podršci! 💚");if(!r.error)refresh();}else if(a==="follow"){if(!user())return;if(S.follows.includes(String(id))){const {error}=await sb().from("fan_team_follows").delete().eq("user_id",user().id).eq("team_id",id);if(error)return note(error.message,"error");}else{const {error}=await sb().from("fan_team_follows").insert({user_id:user().id,team_id:id});if(error)return note(error.message,"error");}refresh();}else if(a==="clubDonate"){const r=await rpc("fan_team_donate",{p_team:$("fgClubTeam").value,p_amount:Number($("fgClubAmt").value)},"Hvala na podršci! 💚");if(!r.error)refresh();}else if(a==="mvp"){const r=await rpc("fan_mvp_vote",{p_match:id,p_player:$("mvpP-"+id).value,p_extra:Number($("mvpX-"+id).value)},"Glas je upisan ⭐");if(!r.error)refresh();}else if(a==="gen"){const r=await adminAction("generate_markets",{match_id:id},"Ponuda je otvorena.");if(!r.error)refresh();}else if(a==="settle"){if(confirm("Obračunati poene za ovu utakmicu?")){const r=await adminAction("settle_match",{match_id:id});if(!r.error)refresh();}}else if(a==="grant"){const r=await adminAction("grant",{user_id:$("grU").value,amount:Number($("grA").value),reason:$("grR").value});if(!r.error)refresh();}}
  function mount(){if($("game"))return;const main=document.querySelector("main");if(!main)return;const sec=document.createElement("section");sec.className="section";sec.id="game";sec.innerHTML=`<h2 class="section-title">🎯 Pogodi</h2><div id="gameRoot"></div>`;main.appendChild(sec);document.addEventListener("click",onClick);document.addEventListener("input",e=>{if(["fgStake","fgBoost"].includes(e.target.id))updateWin();});}
  function boot(){if(!window.showSection||!window.supabaseClient)return setTimeout(boot,250);mount();const orig=window.showSection;window.showSection=function(id){const r=orig.apply(this,arguments);if(id==="game")refresh();return r;};setInterval(()=>{if(document.querySelector(".section.active")?.id==="game")refresh();},10000);window.medjasiGame={refresh};}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
})();